### ISSUE TITLE
I3 multiple monitor different status bar

### ISSUE THREAD

**Issue by MartinMorlot** [tobi-wan-kenobi/dotfiles#1]
Hey Tobi,

Was just wondering how your i3 setup worked with mutliple monitors. Like is the config.{monitor name} automatically detected by i3 or did you have to build it in?

**Comment by tobi-wan-kenobi** [comment]
Heh, excellent question :)

Actually, this templating only works in conjunction with `bumblebee-status` and its `xrandr` module, which has a parameter `overwrite_i3config` (which needs to be set to true explicitly).

If this is set, it invokes a script called "toggle-display.sh", which is part of the bumblebee-status suite. That in turn handles the templating stuff :)

Hope that helps!
